on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image to Docker Hub and GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/ocelot-gateway:1.0.0
            ghcr.io/${{ github.actor }}/ocelot-gateway:1.0.0
            ${{ secrets.DOCKER_USERNAME }}/ocelot-gateway:1.0.0
            ${{ secrets.DOCKER_USERNAME }}/ocelot-gateway:1.0.0
          cache-from: type=gha
          cache-to: type=gha,mode=max
